# Generated by Django 5.1.15 on 2026-09-18 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('shares', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('invite_code', models.CharField(blank=True, max_length=12, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseholdExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.CharField(choices=[('Rent', 'Rent'), ('Electricity', 'Electricity'), ('Gas', 'Gas'), ('Water', 'Water'), ('Wi-Fi', 'Wi-Fi / Internet'), ('Grocery', 'Grocery / Market'), ('Cleaning', 'Cleaning & Maid'), ('Maintenance', 'Maintenance & Repairs'), ('Food', 'Food & Meal'), ('Transportation', 'Transportation'), ('Other', 'Other Household Cost')], default='Grocery', max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='household_receipts/')),
                ('split_method', models.CharField(choices=[('EQUAL', 'Equal Split'), ('EXACT', 'Exact Amount Split'), ('PERCENTAGE', 'Percentage Split'), ('SHARES', 'Share-Based Split')], default='EQUAL', max_length=20)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
    ]
