# Generated by Django 5.1.15 on 2026-09-18 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('budget_warning', 'Budget Warning'), ('budget_exceeded', 'Budget Exceeded'), ('bill_due', 'Bill Due Soon'), ('bill_overdue', 'Bill Overdue'), ('household_invite', 'Household Invitation'), ('expense_added', 'Shared Expense Added'), ('settlement_request', 'Settlement Request'), ('savings_goal', 'Savings Goal Milestone'), ('general', 'General Notification')], default='general', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
