# Generated by Django 5.1.15 on 2026-09-18 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='households.household'),
        ),
    ]
