# Generated by Django 5.1.15 on 2026-09-18 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.CharField(blank=True, default='1 unit', help_text='e.g. 5 kg, 2 liters, 1 dozen', max_length=50)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('actual_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_purchased', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_purchased', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Weekly Grocery', max_length=150)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
