# Generated by Django 5.1.15 on 2026-09-18 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groceries', '0001_initial'),
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='purchased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_groceries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_grocery_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_lists', to='households.household'),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='grocery_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='groceries.grocerylist'),
        ),
    ]
