# Generated by Django 5.1.15 on 2026-09-18 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('both', 'Both')], default='expense', max_length=20)),
                ('icon', models.CharField(default='Tag', max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Credit / Debit Card'), ('mobile_banking', 'Mobile Banking (bKash/Nagad/UPI)'), ('other', 'Other')], default='card', max_length=30)),
                ('merchant', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('source', models.CharField(help_text='e.g. Salary, Freelancing, Dividends', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_frequency', models.CharField(choices=[('none', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=20)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
