# Generated by Django 5.1.15 on 2026-09-18 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(default='Cash', help_text='Cash, bKash, Nagad, Bank, etc.', max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('settled', 'Settled / Completed')], default='settled', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('proof_image', models.FileField(blank=True, null=True, upload_to='settlement_proofs/')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='households.household')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
